// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fr9bhs3En+VwV6B2jh92VaTRkVxcC2nVWA7vlhu0It8DrU7KzHhkhuSK1kNBNxD3BPekxyG3F3t6sNx",
	"e40vONx/XpEcDoe/mfnN0B+DUCWpkiitCXofg5RplqBF7b4G0lgmQxxEl8xO6ZcITah5armSQS+4lvxD",
	"hsAjlJbHHDWoGOwUgecLg0aAdyxJBQa94ODwCLvfPHnaxG+fjZsHh9FRk3W/edLsHj55ctA9eNrtdDpB",
	"I+AkOaX9GoFkCa3kpR5BI9D4IeMao6BndYaNwIRTTBgpl7C7M5QT0vTJUSNIuCw+Dxok0aIm2X9/w5q/",
	"dprPbvbyP5o3HzuNJwfL4vf9v3wVNAK7SGlvYzWXk2C5XNLWJlXSoDPOc6XHPIpQ0keopEVp6U+WpoKH",
	"jEzUfmeUGy6NQBa0jAsynkENkUIDUlmYshlCijrhxnAlwSpgYYjGgJ1yAxqNyrQzqLHMZibodTtHjcBy",
	"62x77OfGpU6l/penr84HV1eDlxe3/dOLwWk/WFZt9pXGOOgFf2qvcND2o6Z9qrXS/uT1e18dfdkIriXL",
	"7FRp/ivdye8yxc9M8AhIDAHJL4BQo8MVEwaYRiju/UGmOaiYpi62hE9poeuL4+vhT6cXw8HJ8fAPsU/N",
	"JMtSnoONX7ThSq+en8DTbztPgfYRnEkLSDOhwFzQCFKtUtSWe/wV1luX9FOWMNnUyCI2Fgh4lwom/dlN",
	"iiGPeUgmdLZTYZhpjeueOpwifE2+9zXEHEUEzsy5+ceZhTnzqE21mvGoaszCXRql024JG68GoDFGtzFh",
	"1itTaucPvkO3ths17QdGk1jphNmgF2SaN8tNt+lbgGfDnsPhJfhBCFVU06bb6ZSSuLQ4QU2icuitS7qa",
	"Km1hWr8fkyUJ04sicqZajQUmtSMP5Mw5yECmmd2muv/hfjPnQXrB5cRt5I3sVlb3mlqbml67HYVJK/+1",
	"FaqksDr3qjR5rspDzbusxu03Qb6tt9NNOVuN32Fo6URXqGc8xOEixcFOHD3PhADjZ7qTlHmnDAqgMdVo",
	"UFrnARtOxCYo7a1PM+viL1iCxbW4eZAwySbegNyUm7XgeEw7gNIgSaX5FCWtGslSH3KYUCOzGMGc26nK",
	"bC5Tq8xyOWmNZO0eUM6abkJzjsY2DygZZkIQZIrERxB6KcWi+N6Ahd/w1vJtpxvyBI1lSVqqCzVtY66N",
	"LXSu3nTELDadzAeoEKFA2vB2l3f18wmFh1E0iAhHFGqK1aY0MQ2z0PJZxbimBVcnP532r89O+8BlRJEe",
	"Tf1E3MCHDDOMnIRQIJNZ2hrJ58eDzVX5MEyZAbwLESOMIGF3PMkS0Gg1R9Mayf7p2emwtrhY6GI40l3v",
	"zbjh5ObOyIIbumt/LowqR9jP719mCflHeZ6gEXgVg0aQ70f+8km78+ghbM2HXoTc24DcDQb/AXf7YxnY",
	"J0+ZbmWlrwrfp+HKcWsHysNGk2Q2y2t4aFb5pGaUy1x8iSJOajFxWYk7ftFacsjvoMiCPmPHSgg1J8wo",
	"WQYjk6Wp0gSvavAbyZxlwN7P51cphg04UdIyLlH7zz6zbMwM+i+l4URkxvrRHIAbgXiX3155d72P7786",
	"Pe7/8hBjZWn0++OUYMaCl/B7w9RacnJ3t5GUGsFdk2HaLOmmq5Ycoo1btR1QH4s/b3m0JKmpyDQTOxFI",
	"LJbLSSaY3jWnkl39cM7CdIuSNlft7auW29PqGTd20+qXlOdctqKYRddc1bCeQ1cj9GExMZ8iztuye0lj",
	"AqY1W9C3xDt7m7IJ3lr13tdZa9ign10U81F5VpAbWgm0kjTXaDJhTT29Ll6kfzsZPBm8O12cH153Loa/",
	"HJ29vu6+fD2w58MX788XB9OL/vXh2fCvi4t3v9xd9E+PLvrH8/OTF8+2sps1xyHPwTDT3C6u6NDeOGNk",
	"GjUVJKuv5wVgX7weButB4cXrIbizgxo7T44g1irxWUrJmE8yypMkES5zFAR5uUHq+C1WChO78wULl7Eq",
	"qjUWEgI2qpj+yTlcXUIZTs+J/WBCafj4cgBNOCFyQFGKychzIz+q4jKj1FgZJc0hMSdazukmaLrZnYIg",
	"FmoOzBAjcIfnOa8i1VBOaY7bkQCpDBM+iAkeIlVMvY9FA+E4ZeEU4bBFwTvTokJ05/N5i7nhltKTdr7W",
	"tM8GJ6cXV6fNw1anNbWJqPD6MlYXJt+7utzfZaegEcxQG2/S2QET6ZQdkDCVomQpD3rBUavT6gY+nTmc",
	"tHfEht7HYIJ2W8azmZYGWOmtW1mxcdQTVOozEsRcWHQIdtpod5mDKOgFFBQGVYevtIXebNBwJ6ayy3hR",
	"27/o6XzIUC9WTZ18ym0+ZVVybzjXQzbcStJdHbVt7wrt/007D2JwGQSMim0zp3EVRZgma4cii0qwFuFn",
	"JJlQcmJ4hDmDrfgF9DFmNIsq85gJgx7JW+02VfPbfOua9pGXEfScgNLnx0oRLd12nPOc08osGfvmXa4s",
	"pKhd/NyhQ8LufGA2/FfcrsQBlcY5aS6+uMy/NovmTeVWwT31ycjXb9vUqeSI+67zZq2Dd9jpPKBh9bBe",
	"0K7MuqU7dJW57lWcCSi9jgJC91518sbAn3+bWjtbVD+wyLV00Fi/98EuUaXJ2vW2Fi06+vSiWq+wRMdj",
	"HfNa4l2KIXkp5nMaQd5yyeMcsF1dBIp8lk0cvStp1A3VHWobZ3LpEIGBxPmKo6oYWE18ayRf5hFYLHK6",
	"vwAGoeBU7jNj+IRy3aA/kjPOXAx5y6O34EAPZShuwSCuNeEaPjfSXqhhzoWACUoCGAKTMOj7mFKP9F7p",
	"Ss13b6gvFIdB33nmVrPtcFJej1aft1l/4yk9GvuDihaf08uLl4Hqo8RyI9AcfH4V1jJVgb+ig/PYAaZo",
	"WvpO4eOFmG6n+3iHvFAWYpXJXNdnj7fziZKx4KGFZul3gz4wQaXugqhHZlxN1T08fDyl3DuOLwnwLsS0",
	"yGzf+Ft8HCUKcp5JNmPcdUyhWTRby0eMRc7NXIzACFLB8lpinFmQKl9grNLVUutLTGJF3pH3JJ3tmWzZ",
	"2FVqrPoWg2jpUx0Rzm2lR6Jmtc1b8ANO2Yy7Rm6KMjKgJMynaKfo2o3atWOZzE1s1UhKZXm86I3kSDbh",
	"2LW9tcrq3HpvRdrBoG24qpNBgsZQoZ9mY8HNFPVIQuXC9nsbjWCUWgmRt4KLFjOt2lvrVn9ftmH3882K",
	"CQVwSFyxceROAqtKpAFjNLaJcay0/c7X7MQ1dF6tHXa6oEgnrxCBj9YboocYmQZonDAdCTSuz1axYLFn",
	"MRcj+Nc//gms+J3ExIyLzJvaN0ciEIzKphz6Ra+a0BdlArU7IjcgceaNaDIds9A/uBbKE+14W/Tn366e",
	"r8MpkxOs6kgSPGjqRiqbNdF3wC0oKRZ0XVYrYdbXr/ropeH3nMVW1R4L30s1FxhN0AC3rq1ZjpIMbnyE",
	"plNIBVSDoQa848buw3vElMrmoktvVTI21rVatVuZCbEgKWmmJxi1CJ6DejVdhgonn2AMe8VvDqxOJanu",
	"AaiTU1r1e1e+vYU9OkYea/Yb6ygmIVOmo1URmiQYcWZRLGo3WcK9Ba+5ddBYbUVk5W1jp4c8xCk8qBKm",
	"32NUXlgOMnfSdZx9bXx7LlyEAh1uCUAV9bfRVPdMdA9N3RZXV1Paa//Isllsvna9ZVfa+97aBvAKqKwg",
	"ojFUOhrJDQvlDzWNElZE46tlu7P7vjM5smgkVQxj5HJSv9H7kO6xUYSuPaVXs6sX6WHbLiNexcoNCn+V",
	"F6hdaN7f3YkoYPTbuhCbVXh3M62U9LUwhimLZrH4r3HZQd+9vQhekNP/PUZbGl5Wqe2XRnl8OKiyjl2l",
	"+tZ+6Y9oa3RpvABuDWT+gXTQ3wg/P6L9fLHnIU1Fzxnyn5FFRAi6nW5rJB+lc/jInbMvtmv2/0DwhQWC",
	"dU9ee/rYUfZUXuecB1ff5d7cENp9E837t38varOUt1fvNzel5I2X8e1PZiVozeb/tQbLm+W/AwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
